# Site settings
title: Arik's Bar Mitzvah!
email: eitan.suez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Get ready for Arik's Bar Mitzvah!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ariksuez.com" # the base hostname & protocol for your site
twitter_username: eitan_suez
github_username:  eitansuez

# Build settings
markdown: kramdown
